name: sparkignite
channels:
  - conda-forge
dependencies:
- python
- numpy
- pip
- numpy
- scipy
- matplotlib
- sympy
- ipython
- ipykernel
- ipyvtklink
- jupyterlab
- jupyterlab_widgets
- ipywidgets
- jupyter-book
- nbconvert
- pandas
- panel
- scikit-learn
- cma
- cadquery
- flask
- ipyvolume
- fvcore
- iopath
- plotly
- pywin32
- quaternion
- multipledispatch 
- kivy

pip:
  - ocp_tessellate webcolors ocp_vscode requests orjson urllib3 certifi